image: python:2.7-alpine

pages:
  before_script:
  - apt-get install git
  - git submodule init
  - git submodule update
  - pip install -r requirements.txt
  script:
  - pelican -s site/pelicanconf.py
  - mv site/output public
  artifacts:
    paths:
    - public
  only:
  - master
