image: python:3.10-rc-alpine

pages:
  script:
  - git submodule update --init
  - pip install -r requirements.txt
  - pelican -s site/pelicanconf.py
  - mv site/output public
  artifacts:
    paths:
    - public
  only:
  - master
